### ISSUE TITLE
XDOODLE-37: Auto-refresh the poll count after save

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-xpoll#14]
Tested on 10.6 with XPoll 1.9.3
Issue: https://jira.xwiki.org/browse/XDOODLE-37

Currently you need to refresh the page manually to see the count change. The Save button gets disabled until the page refresh.
<img width="914" alt="autorefresh" src="https://user-images.githubusercontent.com/629552/43786285-f602ff62-9a70-11e8-9bf6-2e8c651a3c83.png">

**Comment by CostiChD** [comment]
Would you like to refresh the whole page or just the table ?

**Comment by acotiuga** [comment]
I would say we should refresh only the table, for a better user experience.
