### ISSUE TITLE
Poll template is not selected by default at page creation in the Poll space

### ISSUE THREAD

**Issue by CostiChD** [xwikisas/application-xpoll#16]
Steps to reproduce:
1. Go to XPoll/WebHome
2. Click on the "Create" button in order to create a poll

Expected results:
Poll template is already selected.

Actual results:
"Blank page" is selected.

**Comment by CostiChD** [comment]
Duplicated. 
You can check it here: https://github.com/xwikisas/application-xpoll/issues/13

**Comment by oanalavinia** [comment]
I reopened it since this is still reproducing for older versions of xwiki then 9.5
