### ISSUE TITLE
Improve the display of Poll entries

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-xpoll#4]
We can improve the way the display the sheet, by better displaying the columns.
Current
<img width="814" alt="current" src="https://user-images.githubusercontent.com/629552/33134749-37df4906-cfa9-11e7-8f64-56033423f01a.png">

**Comment by CostiChD** [comment]
After https://github.com/xwikisas/application-xpoll/issues/17 was solved, the name label does not appear anymore in view mode. Also, I would like to know if we should(or not) show empty properties(check the "DESCRIPTION" in the image above).

**Comment by evalica** [comment]
This issue is more about improving the sheet of the Polls. For example, the Status could be displayed in another column, similar to what we have for the Meetings. 
Also WebHome should not be displayed, in case that happens. 
Regarding the display of empty properties. I don't have a clean answer for this. For some of our applications we are hiding some fields, where for other we don't. 

* On one hand you want to hide fields that you know the user will not need and they are display not that good, by being empty. A solution for this would be to display an "empty message" like "No description" or something, that could take the value of the placeholder, if the value is empty. 
* On the other hand you want to display that there are fields there, in order to be discoverable and encourage the user to add that information. 

I guess it also depends on the field. Some fields are mandatory, others are not. If in a meeting application, you have added a group, you might not need to add users, so that field could be not displayed. While you kind of always need the Description of the Poll, on order to know what's the point of the Poll. 

So in this particular application and use case, I would not hide the fields, since they are minimal and mandatory. But I would enhance the display of the sheet in view mode, by having an "empty state" text.

**Comment by CostiChD** [comment]
It looks like the problem about showing "WebHome" is fixed here: https://github.com/xwikisas/application-xpoll/issues/11 . I'm going to add another column(trying to see which way is better) and also the "empty state" text/translation.

**Comment by CostiChD** [comment]
I rearranged the labels and moved the "Status" in a second column. I also added a temporary xhint for the "Status" property. I still need to add some translations(for the empty values) .
![xpoll-edit](https://user-images.githubusercontent.com/40485139/44656662-67077a80-aa02-11e8-967d-09533c91b0c4.png)
![xpoll-view](https://user-images.githubusercontent.com/40485139/44656663-67077a80-aa02-11e8-8483-cc74a2d7b5be.png)

**Comment by CostiChD** [comment]
Another thing that we should consider is improving the tables view. Long proposals(long strings) can cause some problems(bad display).

**Comment by CostiChD** [comment]
Moved description after proposals and status:
![xpoll_after_edit](https://user-images.githubusercontent.com/40485139/45161608-f1b35b00-b1f4-11e8-8417-61ddb41d7c21.png)
![xpoll_after_view](https://user-images.githubusercontent.com/40485139/45161609-f1b35b00-b1f4-11e8-9fd1-f666ffcd0e7e.png)
