### ISSUE TITLE
Issues with votes while changing the options multiple/single

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-xpoll#57]
With ticket #41 the option to change from single/multiple and vice-versa was introduced.
 
This new functionality causes an issue while changing the options.

Steps to reproduce:

1. Create a new poll with multiple choices, Status > Active
2. Vote with multiple users
3. Edit the poll and change Type > Can select a single option
4. Save the changes and observe the results

Expected results: Ticket #41 doesn't have any info about how should the votes be saved when changing the option. In this case, a documentation needs to be put in place of what happens when there are multiple selections and the user changes them to single.

Also, need to establish:
1. Can the user change the option in any Status of the poll (In preparation/Active/Finished) ?
2. Can the option be changed any number of times?
3. Should simple user be able to change the option?

At the moment the simple users can do all 3 points.

Actual results: The votes are saved randomly, not even the last selections. Once the poll is changed to single option the total number of votes remain as per Multiple selection.

Environment: XWiki 9.11 Standard with Chrome 77, Polls Application (Pro) 2.0

![Step1](https://user-images.githubusercontent.com/40691112/67666629-debd9600-f974-11e9-8f2f-a31c5e2947e0.jpg)

![Step2](https://user-images.githubusercontent.com/40691112/67666637-e2511d00-f974-11e9-80a6-f9812cd34e9c.jpg)

![Step3](https://user-images.githubusercontent.com/40691112/67666650-e715d100-f974-11e9-8c46-f4a04747a06e.jpg)

![Step4](https://user-images.githubusercontent.com/40691112/67666657-e9782b00-f974-11e9-805f-0619f9840707.jpg)

**Comment by silviamacovei** [comment]
IMO
1. The user should be able to change the option if the Polls are “In preparation”
2. While the poll is in prep, the poll creator should be able to change her mind any number of times
3. The poll creator and admins should be able to change the option.
