### ISSUE TITLE
The username is not well aligned when the name is long.

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-xpoll#68]
![Screenshot from 2020-03-30 08-51-43](https://user-images.githubusercontent.com/12369283/77880109-8876bb00-7264-11ea-9cbb-14c551302c6f.png)

**Comment by petrenkonikita112263** [comment]
Can it be that this was already fixed in some old commit? I didn't see the same on my side on XWiki 11.10 version.

![image](https://user-images.githubusercontent.com/56109799/199173421-1b019051-de73-4bfd-8d79-922f7eae5111.png)

**Comment by oanalavinia** [comment]
Maybe it was fixed by https://github.com/xwikisas/application-xpoll/issues/92 @trrenty ?

**Comment by trrenty** [comment]
The issue should be fixed, yes. Closing it.
