### ISSUE TITLE
Can't vote on a subwiki as a LocalUser and GlobalUsers aren't listed in the poll although they can vote 

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-xpoll#88]
I believe this issue is related to the fix for https://github.com/xwikisas/application-xpoll/issues/61

Preconditions:
- Have 1-2 users created on Main wiki
- Have a subwiki created with "Both global and local users are available in the wiki" and the Polls app installed on farm (so it can be available on Main and subwiki) 
![SubWikiUsers](https://user-images.githubusercontent.com/40691112/141116867-db6f5b3c-36b4-44db-9c40-5aa2b16b3d38.jpg)

Steps to reproduce:

1. Access the subwiki as Admin
2. Add the global users in the subwiki eg. user01, user02
3. Create 2 local users eg. subuser01, subuser02
4. Create a new poll
5. Log in and vote as the local users 
6. Log in and vote as the global users

Expected results: The local users are able to see all the voting users.

Actual results:

1. The local users can't vote - After clicking Save "Failed to save the document. Reason: HTTP" appears and the selections aren't saved

![Step_1](https://user-images.githubusercontent.com/40691112/141114725-2946ad63-a621-40c6-b5e3-82fbbe03b41f.jpg)
![Step_2 After Save Subuser](https://user-images.githubusercontent.com/40691112/141114740-95296c0e-2b62-45de-9198-b4cca9d34952.jpg)

2. Global users can vote, the votes are saved but the users aren't listed in the Poll - other users can only see the Scores not the users that voted

![Step_4 GlobalUser After Save](https://user-images.githubusercontent.com/40691112/141116638-e62e8edd-0a14-4604-9607-b562a6914baa.jpg)
![Admin After GlobalUsers votes](https://user-images.githubusercontent.com/40691112/141116794-d30acf08-84fc-4227-a89e-9f56e251044e.jpg)

Environment: Windows 10, XWiki 13.4.5 MySQL 8.0 and Standard, Polls Application (Pro) 2.1, IE 11, Chrome 95

**Comment by trrenty** [comment]
This issue was fixed by #85
