### ISSUE TITLE
Bug when displaying the user name in the poll table

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-xpoll#92]
This is the same issue as #32, with the same description and maybe slightly different display.

It reproduces on a subwiki, on a farm where the subwikis are configured to domain based and the users from the poll are from the main wiki (the subwiki is configured as having only global users). The cause is that in that case, the URLs of the user profiles are absolute URLs, starting with ```https://``` , which wiki syntax. In a path-pased farm (or when the users are on the same wiki as the poll) the URLs to user profiles are relative, and that is not wiki syntax.

Issue #32 was reintroduced in version 2.1.2 by this commit: https://github.com/xwikisas/application-xpoll/commit/56d490a6997f2c1340f5b35556a82dd34a9a63b7 , which returned to the unsafe usage of the standard #displayUser macro.

**Comment by mflorea** [comment]
``{{html wiki='true'}}`` should really be avoided. @trrenty can you see what changes are needed in order to have just ``{{html clean='false'}}``, i.e. no mixing of HTML and wiki syntax. Thanks.
