### ISSUE TITLE
Options in a long poll are overlapping the right panel

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-xpoll#98]
Issue related to https://github.com/xwikisas/application-xpoll/issues/86

Steps to reproduce:

1. Create a new poll with 15/20 proposals, Status "Active" and Type "Allow multiple options in order"
2. Reduce the browser size

Expected results: The poll is wrapped according to the screen size, in the wiki page, with a scroll option to make it easy for the user to see all options. Eg. as per https://doodle.com/poll/r49e5cfn68gka42m?utm_source=poll&utm_medium=link

Actual results: The last options are overlapping the right panel, surpassing the wiki page area.
![Overlapping](https://user-images.githubusercontent.com/40691112/156016393-33e15283-c63d-405f-bcfd-bd431c27b59c.jpg)

Note: When the last option is near the end of the right panel that is when the scrollbar appears.
![ScrollBar](https://user-images.githubusercontent.com/40691112/156016493-7e580287-f5dd-43c2-ad25-40446347d223.jpg)

Environment: Cloud (XWiki 13.4.3), Chrome 98, Windows 10

Small note: I think a revamping of the UI would be most beneficial in this case, as there were several times that polls with many options were needed (especially in HR cases) and the display is not that great for the users.

**Comment by petrenkonikita112263** [comment]
Can be closed?
